[package]
name = "rdoom"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
bevy = "0.9.1"
bmp = "0.5.0"
lazy_static = "1.4.0"
regex = "1"
serde = "1"
serde_json = "1.0"
thiserror = "1.0"
walkdir = "2"
array2d = "0.3.0"
bevy_flycam = "0.9.0"
bevy_prototype_debug_lines = { version = "0.9", features = ["3d"] }